[bar.default]
attach_panels = false
background_opacity = 0.64999997615814209
capsule = true
capsule_opacity = 0.79999995231628418
end = [ "media", "notifications", "clipboard", "network", "volume", "tray" ]
margin_edge = 0
margin_ends = 0
position = "left"
radius = 0
start = [ "control-center", "battery", "workspaces" ]

[desktop_widgets]
enabled = false

[notification]
layer = "overlay"

[osd]
position = "bottom_center"

[shell]
avatar_path = "/home/maari/.face.jpg"
settings_show_advanced = true

    [shell.panel]
    attach_control_center = false
    transparency_mode = "glass"

    [shell.screen_corners]
    enabled = true
    size = 16

[theme]
builtin = "Kanagawa"

    [theme.templates]
    enable_builtin_templates = false
    enable_community_templates = false

[wallpaper]
directory = "/home/maari/pictures/Wallpapers"

    [wallpaper.automation]
    enabled = true
    interval_minutes = 30
    recursive = false

[weather]
address = "Singapore"
refresh_minutes = 240

[widget.network]
show_label = false

[widget.tray]
drawer = true

[widget.volume]
show_label = false

[widget.workspaces]
display = "none"
empty_color = "tertiary"
